source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

target 'HTNetworking' do

    pod 'Specta', '0.2.1'
    pod 'OCMock', '2.2.4'
    pod 'OCHamcrest', '3.0.1'
    pod 'Expecta', '0.3.1'

    pod 'FMDB'
    pod 'HTCommonUtility'
    pod 'TransitionKit', '~> 2.2'
    pod 'CocoaLumberjack', '~> 2.0'
    pod 'AFNetworking', '~> 2.6.0'
    pod 'RKValueTransformers', '~> 1.1.0'
    pod 'ISO8601DateFormatterValueTransformer', '~> 0.6.1'
    pod 'ReactiveCocoa', '~> 2.1'

end


