source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.hz.netease.com/git/open/HTSpecRepo.git'

inhibit_all_warnings!

def import_pods
  pod 'Specta', '0.2.1'
  pod 'OCMock', '2.2.4'
  pod 'OCHamcrest', '3.0.1'
  pod 'Expecta', '0.3.1'
  
  # Used for testing Value Transformer integration
  pod 'RKCLLocationValueTransformer', '~> 1.1.0'
  
  # Following dependencies are used to replace dependency to RestKit.
  pod 'HTNetworking', :path => '../../'
  pod 'HTNetworking/HTRestKit/Testing', :path => '../../'
  pod 'HTNetworking/HTRestKit/Search', :path => '../../'
  pod 'HTNetworking/HTRestKit/CocoaLumberjack', :path => '../../'
  pod 'TransitionKit', '~> 2.1.0'
  pod 'SOCKit'
  pod 'AFNetworking', '2.6.2'
  pod 'RKValueTransformers', '~> 1.1.0'
  pod 'ISO8601DateFormatterValueTransformer', '~> 0.6.0'
end

target :ios do
  platform :ios, '7.0'
  link_with 'HTHttpTests'
  import_pods

  platform :ios, '7.0'
  pod 'FMDB'
  pod 'ReactiveCocoa', '2.1.8'
  pod 'HTCommonUtility'

end


